SESSION_ID=levanter_22118f6b69d93f4339bbe3764f7f869b31
PREFIX=.
STICKER_PACKNAME=LyFE
ALWAYS_ONLINE=false
RMBG_KEY=null
LANGUAG=en
BOT_LANG=en
WARN_LIMIT=3
FORCE_LOGOUT=false
BRAINSHOP=159501,6pq8dPiYt7PdqHz3
MAX_UPLOAD=200
REJECT_CALL=false
SUDO=+94729101856
TZ=Asia/Colombo
VPS=true
AUTO_STATUS_VIEW=true
SEND_READ=false
AJOIN=true
DISABLE_START_MESSAGE=false
PERSONAL_MESSAGE=true 
MODE=public 
